default:
  debug: true
  digest: false
  compress: false
  interpolator_regex: '\[%(.*?)%\]'
  relative: true

development:
  debug: true

production:
  debug: false
  digest: true
  compress: true
  deploy_strategy: local
  deploy_path: public

old_production:
  debug: false
  digest: true
  compress: true
  deploy_strategy: s3
  aws_key: "AKIAJWMYPVPPS24OHAGQ"
  aws_secret: "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"
  deploy_bucket: "ageoldpun.com"

new_production:
  debug: false
  digest: true
  compress: true
  deploy_strategy: s3
  aws_key: AKIAJYF5DNB6DJQV5IMA
  aws_secret: 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
  # deploy_bucket: www.ageoldpun.com
  deploy_bucket: www.ageoldpun.com.s3.amazonaws.com
