default:
  debug: true
  digest: false
  compress: false
  interpolator_regex: '\[%(.*?)%\]'
  relative: true

development:
  debug: true

production:
  debug: false
  digest: true
  compress: true
  deploy_strategy: s3
  aws_key: "AKIAJWMYPVPPS24OHAGQ"
  aws_secret: "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"
  deploy_bucket: "ageoldpun.com"

